### ISSUE TITLE
Suggestion: Check-in/Check-out to regulate schedule

### ISSUE THREAD

**Issue by emmaarfelt** [AnalogIO/CafeAnalogIOS#3]
We've introduced a feature called "check-in" where baristas on shift check-in when there on shift. This way we have a knowledge of whether people actually showed up or not at their shifts. This way we can also prevent, that people forget to drop their shifts and the costumers expect us to be open because shiftplanning says so :-)

**Comment by cholewa1992** [comment]
We are using the API call www.cafeanalog.dk/api/open/ - That is probably where this should be implemented and not in the app :-)
